### ISSUE TITLE
Can't access (ping/curl) load balancer using the provided external IP Address (Ubuntu 22)

### ISSUE THREAD

**Issue by AyushGlitch** [kubernetes-sigs/cloud-provider-kind#183]
I went through the following steps and the cloud-provider-kind provided an external IP Addr for the load balancer but wasn't able to access the load balancer with it.

OS: Ubuntu 22
Processor: Inter i5 1135g7

### Creating Kind Cluster ###
> clustersConfig.yaml
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
  - role: worker
  - role: worker
```

`$ kind create cluster --config clustersConfig.yaml`

![image](https://github.com/user-attachments/assets/2e9123b7-20a2-4cd3-a7cb-019f283e1463)
![image](https://github.com/user-attachments/assets/73072926-be35-4fe1-97f1-63435d7f46be)

### Creating Load Balancer Deployment ###
> loadBalancerDeply.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zeroapp
spec:
  selector:
    matchLabels:
      app: zeroapp
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: zeroapp
    spec:
      terminationGracePeriodSeconds: 30
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - zeroapp
            topologyKey: kubernetes.io/hostname
      containers:
      - name: zeroapp
        image: registry.k8s.io/e2e-test-images/agnhost:2.39
        args:
          - netexec
          - --http-port=80
          - --delay-shutdown=30
        ports:
          - name: httpd
            containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: zeroapp
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: zeroapp
  ports:
    - name: httpd
      port: 80
      targetPort: 80
```

`$ kubectl apply -f loadBalancerDeply.yaml`

![image](https://github.com/user-attachments/assets/2e2e2b92-948b-428b-b134-b0d79d8f3253)

### Allowing load balancers access to control plane nodes ###
`$ kubectl label node kind-control-plane node.kubernetes.io/exclude-from-external-load-balancers-`

![image](https://github.com/user-attachments/assets/37ab56b2-c678-44f0-b638-ec6af90f7d8f)

### Staring cloud-provider-kind ###
`$ cloud-provider-kind`

![image](https://github.com/user-attachments/assets/038fd902-d770-49ef-9c36-9e75380bf42d)

> External IP provided
![image](https://github.com/user-attachments/assets/d032f655-9b62-488c-9cce-fdaec1696d6f)

### Access Load Balancer  (Not Working) ###
`$ curl  172.22.0.5:80/hostname`

![image](https://github.com/user-attachments/assets/a1221105-36f2-4f7f-9cec-08b24716dbac)

**Did I miss any of the steps ? 
If not then, is there any setting that has to be changed or any permission that should be provided ?**
