### ISSUE TITLE
cloud-provider-kind freezes my system when using istio

### ISSUE THREAD

**Issue by iblancasa** [kubernetes-sigs/cloud-provider-kind#78]
The [Istio documentation for kind](https://istio.io/latest/docs/setup/platform-setup/kind/) points to `Cloud Provider KIND` to setup `MetalLB`.

I'm using `kind` `0.23.0` and `cloud-provider-kind` `0.1.0`. 

When I start a `kind` cluster with this configuration:
```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: kindest/node:v1.29.4@sha256:3abb816a5b1061fb15c6e9e60856ec40d56b7b52bcea5f5f1350bc6e2320b6f8
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP
```

Everything works properly when I start `cloud-provider-kind`. When I start `istio` version `1.22.0` with `istioctl install -y`, the system freezes. After that, I have to reboot.

I'm running `Fedora release 39 (Thirty Nine)`.
